version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies"
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update && sudo apt-get install -y terraform
      - terraform version
  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init
  build:
    commands:
      - echo "Running Terraform plan"
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan
artifacts:
  files:
    - '**/*'