version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies"
      - terraform version
  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init
  build:
    commands:
      - echo "Running Terraform plan"
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan
artifacts:
  files:
    - '**/*'